name: Build all pages

on:
  pull_request:
    branches: ["master"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        react-dir:
          - MatchScouting
          - PitScouting
          - SuperScouting
          - MatchData
      fail-fast: false

    defaults:
      run:
        working-directory: ./${{ matrix.react-dir }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          cache-dependency-path: ${{ matrix.react-dir }}/package-lock.json

      - run: npm ci

      - name: Build app
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: build-${{ matrix.react-dir }}
          # Path of the directory containing the static assets.
          path: ${{ matrix.react-dir }}/build
