name: Build all pages

on:
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        react-dir: [ "MatchScouting", "PitScouting", "SuperScouting" ]

    defaults:
      run:
        working-directory: ./${{ react-dir }}

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: ${{ react-dir }}/package-lock.json
      
      - run: npm ci
      
      - name: Build app
        env:
          CI: false
        run: npm run build
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: build-${{ react-dir }}
          # Path of the directory containing the static assets.
          path: ${{ react-dir }}/build
