name: Build app for tablets

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./MatchScouting

    steps:
      - uses: actions/checkout@v3
        
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      
      - run: npm ci
        
      - name: Build app for tablet
        run: npm run build-tablet
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: build
          path: build
