name: Build app for tablets

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - run: npm install
      
      - name: Build app for tablet
        run: ./tablet-build.sh
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: build
          path: build
